import { useEffect, useState } from 'react'
import type { ChangeEvent, FormEvent, ReactNode } from 'react'
import { ArrowRight, Check, FileText, LockKeyhole, ShieldCheck, Truck, Upload, UserRound } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { supabase } from './lib/supabase'
import './App.css'

type Step = 'account' | 'otp' | 'personal' | 'identity' | 'vehicle' | 'documents' | 'review' | 'complete'
type FormData = Record<string, string>
type FileData = Record<string, File>
const steps = ['personal', 'identity', 'vehicle', 'documents', 'review'] as const
const documentTypes: Record<string, string> = { idFront: 'national_id_front', idBack: 'national_id_back', selfie: 'selfie', license: 'license_front', registration: 'vehicle_registration', insurance: 'insurance' }

function App() {
  const [step, setStep] = useState<Step>('account')
  const [mode, setMode] = useState<'register' | 'login'>('register')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [form, setForm] = useState<FormData>({})
  const [otp, setOtp] = useState(['', '', '', '', '', ''])
  const [files, setFiles] = useState<FileData>({})
  const [driverId, setDriverId] = useState('')
  const [applicationStatus, setApplicationStatus] = useState('pending_review')
  const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const go = (next: Step) => { setError(''); setStep(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  useEffect(() => {
    const restoreApplication = async () => {
      if (!supabase) return
      const { data: userData } = await supabase.auth.getUser()
      if (!userData.user) return
      const { data: driver } = await supabase.from('drivers').select('id, application_status, full_name, email, phone').eq('auth_user_id', userData.user.id).maybeSingle()
      if (!driver) return
      setDriverId(driver.id); setApplicationStatus(driver.application_status); setForm((current) => ({ ...current, fullName: driver.full_name, email: driver.email, phone: driver.phone }))
      if (driver.application_status !== 'draft') setStep('complete')
    }
    void restoreApplication()
  }, [])
  const fail = (message: string) => { setLoading(false); setError(message) }
  const requireClient = () => { if (!supabase) { fail('Supabase is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local.'); return false } return true }
  const saveDriver = async (userId: string) => {
    if (!supabase) return false
    const { data, error: saveError } = await supabase.from('drivers').upsert({ auth_user_id: userId, full_name: form.fullName || '', email: form.email || '', phone: form.phone || '' }, { onConflict: 'auth_user_id' }).select('id').single()
    if (saveError) { fail(saveError.message); return false }
    setDriverId(data.id); return true
  }
  const accountSubmit = async (event: FormEvent) => {
    event.preventDefault(); setError('')
    if (!requireClient() || !form.email || !form.password || (mode === 'register' && (!form.fullName || !form.phone))) { if (!form.email || !form.password || (mode === 'register' && (!form.fullName || !form.phone))) fail('Complete all required fields to continue.'); return }
    setLoading(true)
    if (mode === 'register') {
      const { data: signupData, error: authError } = await supabase!.auth.signUp({ email: form.email, password: form.password, options: { data: { full_name: form.fullName, phone: form.phone } } })
      const existingAccount = authError?.message.toLowerCase().includes('already registered') || authError?.message.toLowerCase().includes('already exists') || signupData.user?.identities?.length === 0
      if (existingAccount) { fail('An account with this email already exists. Sign in instead.'); return }
      if (authError) { fail(authError.message); return }
      setLoading(false); go('otp')
    } else {
      const { data, error: authError } = await supabase!.auth.signInWithPassword({ email: form.email, password: form.password })
      if (authError || !data.user) { fail(authError?.message || 'Unable to sign in.'); return }
      const { data: driver } = await supabase!.from('drivers').select('id, application_status, full_name, phone').eq('auth_user_id', data.user.id).maybeSingle()
      if (driver) { setDriverId(driver.id); setApplicationStatus(driver.application_status); update('fullName', driver.full_name); update('phone', driver.phone) }
      setLoading(false); go('personal')
    }
  }
  const verifyOtp = async (submittedOtp = otp.join('')) => {
    if (!requireClient()) return
    const token = submittedOtp; if (token.length !== 6) { fail('Enter the 6-digit code from your email.'); return }
    setLoading(true)
    const { data, error: verifyError } = await supabase!.auth.verifyOtp({ email: form.email, token, type: 'signup' })
    if (verifyError || !data.user) { fail(verifyError?.message || 'That code is invalid or expired. Request a new one and try again.'); return }
    if (!await saveDriver(data.user.id)) return
    setLoading(false); go('personal')
  }
  const resendOtp = async () => { if (!supabase) { fail('Supabase is not configured.'); return }; const { error: resendError } = await supabase.auth.resend({ type: 'signup', email: form.email }); if (resendError) fail(resendError.message); else setError('A new verification code was sent.') }
  const savePersonal = async () => { if (!requireClient()) return; setLoading(true); const { data: userData } = await supabase!.auth.getUser(); if (!userData.user || !await saveDriver(userData.user.id)) return; const { error: saveError } = await supabase!.from('drivers').update({ full_name: form.fullName, dob: form.dob || null, national_id: form.nationalId || null, address: form.address || null, city: form.city || null, emergency_contact_name: form.emergencyName || null, emergency_contact_phone: form.emergencyPhone || null }).eq('id', driverId); if (saveError) { fail(saveError.message); return }; setLoading(false); go('identity') }
  const saveVehicle = async () => { if (!requireClient() || !driverId) { fail('Your driver profile is not ready. Please sign in again.'); return }; if (!form.type) { fail('Choose a vehicle type to continue.'); return }; setLoading(true); const { error: saveError } = await supabase!.from('vehicles').upsert({ driver_id: driverId, type: form.type.toLowerCase(), make: form.make || null, model: form.model || null, year: form.year ? Number(form.year) : null, plate_number: form.plate || null, color: form.color || null }, { onConflict: 'driver_id' }); if (saveError) { fail(saveError.message); return }; setLoading(false); go('documents') }
  const uploadDocuments = async () => { if (!requireClient() || !driverId) { fail('Your driver profile is not ready. Please sign in again.'); return }; if (!Object.keys(files).length) { fail('Add at least one document before continuing.'); return }; setLoading(true); const { data: userData } = await supabase!.auth.getUser(); if (!userData.user) { fail('Your session has expired. Please sign in again.'); return }
    for (const [key, file] of Object.entries(files)) { const path = `${userData.user.id}/${documentTypes[key]}-${Date.now()}-${file.name}`; const { error: uploadError } = await supabase!.storage.from('driver-documents').upload(path, file, { upsert: false }); if (uploadError) { fail(`Could not upload ${file.name}: ${uploadError.message}`); return }; const { error: rowError } = await supabase!.from('documents').upsert({ driver_id: driverId, document_type: documentTypes[key], file_url: path }, { onConflict: 'driver_id,document_type' }); if (rowError) { fail(rowError.message); return } }
    setLoading(false); go('review')
  }
  const submitApplication = async () => { if (!requireClient() || !driverId) { fail('Your driver profile is not ready. Please sign in again.'); return }; setLoading(true); const { error: submitError } = await supabase!.from('drivers').update({ application_status: 'pending_review' }).eq('id', driverId); if (submitError) { fail(submitError.message); return }; setApplicationStatus('pending_review'); setLoading(false); go('complete') }
  const handleFile = (key: string, event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (file) setFiles((current) => ({ ...current, [key]: file })) }
  const setOtpDigit = (index: number, value: string) => { const digit = value.replace(/\D/g, '').slice(-1); const nextOtp = otp.map((item, itemIndex) => itemIndex === index ? digit : item); setOtp(nextOtp); if (digit && index < 5) document.getElementById(`otp-${index + 1}`)?.focus(); else if (!digit && index > 0) document.getElementById(`otp-${index - 1}`)?.focus(); if (nextOtp.every(Boolean)) void verifyOtp(nextOtp.join('')) }
  const currentIndex = steps.indexOf(step as typeof steps[number])
  if (step === 'complete') return <main className="complete-page"><div className="complete-mark"><Check size={32} /></div><p className="eyebrow">Application received</p><h1>You’re on your way.</h1><p className="complete-copy">Your driver application has been submitted. We’ll notify you by email once it has been reviewed.</p><div className="reference"><span>Application ID</span><strong>{driverId || 'Submitted'}</strong></div><div className="status-row"><span className="status-dot" /> {applicationStatus.replace('_', ' ')}</div></main>
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Truck size={20} /></span><span>takeoff</span></div><div className="sidebar-copy"><p className="eyebrow">Driver network</p><h2>Move with<br /><em>purpose.</em></h2><p>Join a trusted network moving people and possibility across the city.</p></div><div className="side-foot"><ShieldCheck size={16} /> Your data is encrypted and secure</div></aside><main className="main"><header className="topbar"><div className="mobile-brand"><span className="brand-mark"><Truck size={18} /></span> takeoff</div><span>Already have an account? <button className="link-button" onClick={() => { setMode('login'); go('account') }}>Sign in</button></span></header>{step !== 'account' && step !== 'otp' && <Stepper currentIndex={currentIndex} /> }<AnimatePresence mode="wait"><motion.section key={step} className="content" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -10 }} transition={{ duration: .22 }}>{step === 'account' && <Account mode={mode} setMode={setMode} form={form} update={update} error={error} loading={loading} submit={accountSubmit} />}{step === 'otp' && <Otp email={form.email} otp={otp} setOtpDigit={setOtpDigit} onContinue={verifyOtp} onBack={() => go('account')} loading={loading} error={error} resend={resendOtp} />}{step === 'personal' && <Personal form={form} update={update} onContinue={savePersonal} loading={loading} error={error} />}{step === 'identity' && <Identity files={files} handleFile={handleFile} onContinue={() => go('vehicle')} onBack={() => go('personal')} />}{step === 'vehicle' && <Vehicle form={form} update={update} onContinue={saveVehicle} onBack={() => go('identity')} loading={loading} error={error} />}{step === 'documents' && <Documents files={files} handleFile={handleFile} onContinue={uploadDocuments} onBack={() => go('vehicle')} loading={loading} error={error} />}{step === 'review' && <Review form={form} files={files} onEdit={go} onContinue={submitApplication} onBack={() => go('documents')} loading={loading} error={error} />}</motion.section></AnimatePresence></main></div>
}
function Stepper({ currentIndex }: { currentIndex: number }) { return <div className="stepper">{['Personal', 'Identity', 'Vehicle', 'Documents', 'Review'].map((label, index) => <div className={`step ${index <= currentIndex ? 'active' : ''}`} key={label}><span>{index < currentIndex ? <Check size={13} /> : index + 1}</span><label>{label}</label></div>)}</div> }
function Header({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) { return <div className="form-header"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div> }
function Button({ children, onClick, type = 'button', loading = false, secondary = false }: { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; loading?: boolean; secondary?: boolean }) { return <button type={type} className={`primary-button ${secondary ? 'secondary-button' : ''}`} onClick={onClick} disabled={loading}>{loading ? <span className="spinner" /> : children}{!loading && !secondary && <ArrowRight size={17} />}</button> }
function Field({ label, value = '', onChange, type = 'text', placeholder }: { label: string; value?: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="field"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label> }
function Account({ mode, setMode, form, update, error, loading, submit }: { mode: 'register' | 'login'; setMode: (mode: 'register' | 'login') => void; form: FormData; update: (key: string, value: string) => void; error: string; loading: boolean; submit: (event: FormEvent) => void }) { return <><Header eyebrow="Welcome to takeoff" title={mode === 'register' ? 'Become a driver.' : 'Welcome back.'} copy={mode === 'register' ? 'Complete your profile and get on the road with confidence.' : 'Sign in to continue your driver application.'} /><div className="mode-toggle"><button className={mode === 'register' ? 'selected' : ''} onClick={() => setMode('register')}>Create account</button><button className={mode === 'login' ? 'selected' : ''} onClick={() => setMode('login')}>Sign in</button></div><form onSubmit={submit} className="form-grid">{mode === 'register' && <><Field label="Full name" value={form.fullName} onChange={(v) => update('fullName', v)} placeholder="Tendai Moyo" /><Field label="Phone number" value={form.phone} onChange={(v) => update('phone', v)} placeholder="+263 77 123 4567" /></>}<Field label="Email address" type="email" value={form.email} onChange={(v) => update('email', v)} placeholder="tendai@example.co.zw" /><Field label="Password" type="password" value={form.password} onChange={(v) => update('password', v)} placeholder="At least 8 characters" /><Button type="submit" loading={loading}>{mode === 'register' ? 'Create account' : 'Sign in'}</Button></form>{error && <p className="error-text">{error}</p>}<p className="security-note"><LockKeyhole size={14} /> Your information is encrypted.</p></> }
function Otp({ email, otp, setOtpDigit, onContinue, onBack, loading, error, resend }: { email: string; otp: string[]; setOtpDigit: (index: number, value: string) => void; onContinue: () => void; onBack: () => void; loading: boolean; error: string; resend: () => void }) { return <><Header eyebrow="Verify your email" title="Check your inbox." copy={`We sent a 6-digit verification code to ${email || 'your email address'}.`} /><div className="otp-wrap"><div className="otp-inputs">{otp.map((digit, index) => <input id={`otp-${index}`} key={index} inputMode="numeric" maxLength={1} value={digit} onChange={(event) => setOtpDigit(index, event.target.value)} />)}</div>{error && <p className="error-text">{error}</p>}<p className="resend">Didn’t get a code? <button className="link-button" onClick={resend}>Resend code</button></p></div><div className="form-actions"><Button onClick={onContinue} loading={loading}>Verify email</Button><Button onClick={onBack} secondary>Back</Button></div></> }
function Personal({ form, update, onContinue, loading, error }: { form: FormData; update: (key: string, value: string) => void; onContinue: () => void; loading: boolean; error: string }) { return <><Header eyebrow="Step 1 of 5" title="Let’s get to know you." copy="Tell us a little about yourself and who we can reach in an emergency." /><div className="form-grid two-col"><Field label="Full name" value={form.fullName} onChange={(v) => update('fullName', v)} /><Field label="Date of birth" type="date" value={form.dob} onChange={(v) => update('dob', v)} /><Field label="National ID number" value={form.nationalId} onChange={(v) => update('nationalId', v)} placeholder="12-34566789A00" /><Field label="City" value={form.city} onChange={(v) => update('city', v)} placeholder="Harare" /><Field label="Residential address" value={form.address} onChange={(v) => update('address', v)} placeholder="12 Samora Machel Avenue, Avondale" /><span /><Field label="Emergency contact name" value={form.emergencyName} onChange={(v) => update('emergencyName', v)} placeholder="Rudo Moyo" /><Field label="Emergency contact phone" value={form.emergencyPhone} onChange={(v) => update('emergencyPhone', v)} placeholder="+263 71 987 6543" /></div>{error && <p className="error-text">{error}</p>}<div className="form-actions"><Button onClick={onContinue} loading={loading}>Save and continue</Button></div></> }
function UploadBox({ label, hint, file, onChange }: { label: string; hint: string; file?: File; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className={`upload-box ${file ? 'has-file' : ''}`}><input type="file" accept="image/*,.pdf" onChange={onChange} />{file ? <><div className="file-icon"><Check size={20} /></div><div><strong>{file.name}</strong><small>{Math.ceil(file.size / 1024)} KB ready to upload</small></div></> : <><div className="upload-icon"><Upload size={19} /></div><div><strong>{label}</strong><small>{hint}</small></div></>}</label> }
function Identity({ files, handleFile, onContinue, onBack }: { files: FileData; handleFile: (key: string, event: ChangeEvent<HTMLInputElement>) => void; onContinue: () => void; onBack: () => void }) { return <><Header eyebrow="Step 2 of 5" title="Prove it’s you." copy="Upload clear photos of your identity documents." /><div className="upload-list"><UploadBox label="ID front" hint="PNG, JPG or PDF · max 10MB" file={files.idFront} onChange={(e) => handleFile('idFront', e)} /><UploadBox label="ID back" hint="PNG, JPG or PDF · max 10MB" file={files.idBack} onChange={(e) => handleFile('idBack', e)} /><UploadBox label="Selfie photo" hint="A clear photo of your face" file={files.selfie} onChange={(e) => handleFile('selfie', e)} /></div><div className="form-actions"><Button onClick={onContinue}>Save and continue</Button><Button onClick={onBack} secondary>Back</Button></div></> }
function Vehicle({ form, update, onContinue, onBack, loading, error }: { form: FormData; update: (key: string, value: string) => void; onContinue: () => void; onBack: () => void; loading: boolean; error: string }) { return <><Header eyebrow="Step 3 of 5" title="What will you drive?" copy="Tell us about the vehicle you’ll use to make deliveries." /><div className="vehicle-types">{['Bike', 'Car', 'Van', 'Truck'].map((type) => <button key={type} className={form.type === type ? 'selected' : ''} onClick={() => update('type', type)}><Truck size={21} /><span>{type}</span></button>)}</div><div className="form-grid two-col"><Field label="Make" value={form.make} onChange={(v) => update('make', v)} placeholder="Toyota" /><Field label="Model" value={form.model} onChange={(v) => update('model', v)} placeholder="Corolla Quest" /><Field label="Year" value={form.year} onChange={(v) => update('year', v)} placeholder="2022" /><Field label="Plate number" value={form.plate} onChange={(v) => update('plate', v)} placeholder="ABC 1234" /><Field label="Color" value={form.color} onChange={(v) => update('color', v)} placeholder="Silver" /></div>{error && <p className="error-text">{error}</p>}<div className="form-actions"><Button onClick={onContinue} loading={loading}>Save and continue</Button><Button onClick={onBack} secondary>Back</Button></div></> }
function Documents({ files, handleFile, onContinue, onBack, loading, error }: { files: FileData; handleFile: (key: string, event: ChangeEvent<HTMLInputElement>) => void; onContinue: () => void; onBack: () => void; loading: boolean; error: string }) { return <><Header eyebrow="Step 4 of 5" title="The important paperwork." copy="Almost there. Add the documents that keep every journey covered." /><div className="upload-list"><UploadBox label="Driver’s license" hint="Front and back · max 10MB" file={files.license} onChange={(e) => handleFile('license', e)} /><UploadBox label="Vehicle registration" hint="PNG, JPG or PDF · max 10MB" file={files.registration} onChange={(e) => handleFile('registration', e)} /><UploadBox label="Insurance certificate" hint="PNG, JPG or PDF · max 10MB" file={files.insurance} onChange={(e) => handleFile('insurance', e)} /></div>{error && <p className="error-text">{error}</p>}<div className="form-actions"><Button onClick={onContinue} loading={loading}>Review application</Button><Button onClick={onBack} secondary>Back</Button></div></> }
function Review({ form, files, onEdit, onContinue, onBack, loading, error }: { form: FormData; files: FileData; onEdit: (step: Step) => void; onContinue: () => void; onBack: () => void; loading: boolean; error: string }) { return <><Header eyebrow="Step 5 of 5" title="Ready for takeoff?" copy="Review your details before sending your application to our team." /><div className="review-list"><ReviewBlock title="Personal details" icon={<UserRound size={17} />} onEdit={() => onEdit('personal')}><span>{form.fullName || 'Not provided'}</span><span>{form.email || 'Email not provided'}</span><span>{form.city || 'City not provided'}</span></ReviewBlock><ReviewBlock title="Vehicle" icon={<Truck size={17} />} onEdit={() => onEdit('vehicle')}><span>{form.type || 'Vehicle'} · {form.make || 'Make'} {form.model || ''}</span><span>{form.plate || 'Plate not provided'}</span></ReviewBlock><ReviewBlock title="Documents" icon={<FileText size={17} />} onEdit={() => onEdit('documents')}><span>{Object.keys(files).length} files ready for upload</span></ReviewBlock></div>{error && <p className="error-text">{error}</p>}<div className="form-actions"><Button onClick={onContinue} loading={loading}>Submit application</Button><Button onClick={onBack} secondary>Back</Button></div></> }
function ReviewBlock({ title, icon, onEdit, children }: { title: string; icon: ReactNode; onEdit: () => void; children: ReactNode }) { return <div className="review-block"><div className="review-title"><span>{icon}</span><strong>{title}</strong><button onClick={onEdit}>Edit</button></div><div className="review-values">{children}</div></div> }
export default App
